; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27030.1 

	TITLE	D:\Projects\Presentations.hg\Content\Assembler\Intel\x86\code\constructs.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	_ifLoop
PUBLIC	_forLoop
PUBLIC	_main
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
; {{## BEGIN main-1 ##}}
_DATA	SEGMENT
$SG7450	DB	'Hello, world, this is the %d loop', 0aH, 00H
_DATA	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_result$ = -4 ; size = 4
_argc$ = 8	  ; size = 4
_argv$ = 12	  ; size = 4
_main	PROC  ; Line 24
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 25
	mov	eax, DWORD PTR _argc$[ebp]
	push	eax
	call	_ifLoop
	add	esp, 4
	mov	DWORD PTR _result$[ebp], eax
; {{## END main-1 ##}}
; {{## BEGIN main-2 ##}}
; Line 26
	call	_forLoop
; Line 27
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
; {{## END main-2 ##}}
_TEXT	ENDS
; Function compile flags: /Odtp
; {{## BEGIN forLoop-1 ##}}
_TEXT	SEGMENT
_i$1 = -4 ; size = 4
_forLoop PROC
; Line 16
	push	ebp
	mov	ebp, esp
	push	ecx
; {{## END forLoop-1 ##}}
; {{## BEGIN forLoop-2 ##}}
; Line 17
	mov	DWORD PTR _i$1[ebp], 0
	jmp	SHORT $LN4@forLoop
$LN2@forLoop:
	mov	eax, DWORD PTR _i$1[ebp]
	add	eax, 1
	mov	DWORD PTR _i$1[ebp], eax
$LN4@forLoop:
	cmp	DWORD PTR _i$1[ebp], 10	; 0000000aH
	jge	SHORT $LN1@forLoop
; Line 19
	mov	ecx, DWORD PTR _i$1[ebp]
	push	ecx
	push	OFFSET $SG7450
	call	_printf
	add	esp, 8
; Line 20
	jmp	SHORT $LN2@forLoop
$LN1@forLoop:
; {{## END forLoop-2 ##}}
; {{## BEGIN forLoop-3 ##}}
; Line 21
	mov	esp, ebp
	pop	ebp
	ret	0
_forLoop ENDP
_TEXT	ENDS
; {{## END forLoop-3 ##}}
; Function compile flags: /Odtp
; {{## BEGIN ifLoop-1 ##}}
_TEXT	SEGMENT
_arg$ = 8	; size = 4
_ifLoop	PROC
; Line 4
	push	ebp
	mov	ebp, esp
; Line 5
	cmp	DWORD PTR _arg$[ebp], 5
	jge	SHORT $LN2@ifLoop
; Line 7
	mov	eax, 12	; 0000000cH
	jmp	SHORT $LN1@ifLoop
; Line 8
	jmp	SHORT $LN1@ifLoop
$LN2@ifLoop:
; Line 11
	mov	eax, 17	; 00000011H
$LN1@ifLoop:
; Line 13
	pop	ebp
	ret	0
_ifLoop	ENDP
_TEXT	ENDS
; {{## END ifLoop-1 ##}}
; Function compile flags: /Odtp
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8	; size = 4
__ArgList$ = -4	; size = 4
__Format$ = 8	; size = 4
_printf	PROC	; COMDAT
; File c:\program files (x86)\windows kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 954
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 957
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 958
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 959
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 960
	mov	eax, DWORD PTR __Result$[ebp]
; Line 961
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File c:\program files (x86)\windows kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 642
	push	ebp
	mov	ebp, esp
; Line 643
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 644
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File c:\program files (x86)\windows kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
; Line 86
	push	ebp
	mov	ebp, esp
; Line 88
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 89
	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
