; {{## BEGIN prelude ##}}
; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27905.0 

	TITLE	D:\Projects\Presentations.hg\Content\Assembler\Intel\x86\code\hello.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_add
PUBLIC	_main
; {{## END prelude ##}}

; {{## BEGIN main-1 ##}}
; Function compile flags: /Odtp
_TEXT	SEGMENT
_z$ = -12						; size = 4
_x$ = -8						; size = 4
_y$ = -4						; size = 4
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_main	PROC
; File D:\Projects\Presentations.hg\Content\Assembler\Intel\x86\code\hello.c
; Line 9
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 10
	mov	DWORD PTR _x$[ebp], 1
; Line 11
	mov	DWORD PTR _y$[ebp], 2
; {{## END main-1 ##}}
; {{## BEGIN main-2 ##}}
; Line 12
	mov	eax, DWORD PTR _y$[ebp]
	push	eax
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	call	_add
	add	esp, 8
	mov	DWORD PTR _z$[ebp], eax
; Line 13
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; {{## END main-2 ##}}
; {{## BEGIN add ##}}
; Function compile flags: /Odtp
_TEXT	SEGMENT
_left$ = 8						; size = 4
_right$ = 12						; size = 4
_add	PROC
; File D:\Projects\Presentations.hg\Content\Assembler\Intel\x86\code\hello.c
; Line 4
	push	ebp
	mov	ebp, esp
; Line 5
	mov	eax, DWORD PTR _left$[ebp]
	add	eax, DWORD PTR _right$[ebp]
; Line 6
	pop	ebp
	ret	0
_add	ENDP
_TEXT	ENDS
; {{## END add ##}}
END
